apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
  nodeMeshMaxRestartTime: 120s
  asNumber: 64512
  #serviceLoadBalancerIPs:
  #  - cidr: 10.0.3.0/24
  listenPort: 179
  bindMode: NodeIP
