apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: my-global-peer
spec:
  peerIP: 10.2.0.1
  asNumber: 64512
  nodeSelector: zerotesting == 'fragment'
  filters:
    - only-publish-loadbalancers
