kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "authentik-db"
  namespace: "authentik"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "15"
  dockerImage: zorlin/spilo-15:3.0-p1
  numberOfInstances: 3
  volume:
    size: "8Gi"
    storageClass: rook-ceph-block
  users:
    authentik: []
  databases:
    authentik: authentik
#  allowedSourceRanges:
    # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
