kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cubefs-dstcodex
provisioner: csi.cubefs.com
reclaimPolicy: Retain
parameters:
  masterAddr: cubefs.per.riff.cc:17010
  owner: "dstcodex"
  logLevel: "debug"
  authenticate: "true"
  clientKey: redacted
