apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cubefs-testclaim
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: cubefs-dstcodex
