kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "awx-db"
  namespace: "awx"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "15"
    parameters:
      synchronous_commit: "off"
  numberOfInstances: 3
  volume:
    size: "50Gi"
  users:
    awx: []
  databases:
    awx: awx
  allowedSourceRanges:
    # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
