apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "debian-12"
  namespace: "vm-images"
spec:
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  source:
    http:
      url: "https://cloud.debian.org/images/cloud/bookworm/20240211-1654/debian-12-generic-amd64-20240211-1654.qcow2"
