apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
  namespace: redis
spec:
  redis:
    replicas: 6
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 800m
        memory: 900Mi
