apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cubefs-authnode01-vlan20
  namespace: cubefs
spec:
  config: '{
            "cniVersion": "0.3.0",
            "name": "cubefs-authnode02-vlan20",
            "type": "bridge",
            "bridge": "vlan20",
            "ipam": {
                "type": "static",
                "addresses": [
                  {
                    "address": "10.0.20.90/24",
                    "gateway": "10.0.20.1"
                  }
                ]
              }
            }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cubefs-authnode02-vlan20
  namespace: cubefs
spec:
  config: '{
            "cniVersion": "0.3.0",
            "name": "cubefs-authnode02-vlan20",
            "type": "bridge",
            "bridge": "vlan20",
            "ipam": {
                "type": "static",
                "addresses": [
                  {
                    "address": "10.0.20.92/24",
                    "gateway": "10.0.20.1"
                  }
                ]
              }
            }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cubefs-authnode03-vlan20
  namespace: cubefs
spec:
  config: '{
            "cniVersion": "0.3.0",
            "name": "cubefs-authnode02-vlan20",
            "type": "bridge",
            "bridge": "vlan20",
            "ipam": {
                "type": "static",
                "addresses": [
                  {
                    "address": "10.0.20.93/24",
                    "gateway": "10.0.20.1"
                  }
                ]
              }
            }'
