apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: zerotesting-ovs-vlan64
  namespace: kube-system
spec:
  config: '{
            "cniVersion": "0.3.0",
            "name": "zerotesting",
            "type": "bridge",
            "bridge": "br0",
            "mode": "bridge",
            "ipam": {
                "type": "whereabouts",
                "ipRanges": [{
                    "range": "10.2.2.1-10.2.255.254/16"
                }]
              }
           }'
