apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: storage-vlan20
  namespace: default
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "bond0.20",
            "mode": "bridge",
            "ipam": {
                "type": "whereabouts",
                "ipRanges": [{
                    "range": "10.0.20.220-10.0.20.240/24"
                }]
              }
           }'
