apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: calico-default
  namespace: zerotesting
spec:
  config: |-
    {
      "type": "calico",
      "log_level": "info",
      "datastore_type": "kubernetes",
      "nodename_file_optional": false,
      "ipam": {
        "type": "calico-ipam",
        "assign_ipv4" : "true",
        "assign_ipv6" : "false"
      },
      "policy": {
        "type": "k8s"
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    }