apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: zerotesting
  namespace: zerotesting
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "vlan0",
            "mode": "bridge",
            "ipam": {
                "type": "whereabouts",
                "ipRanges": [{
                    "range": "10.1.3.1-10.1.50.1/16"
                }]
              }
           }'
