apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: zerovm-vlan2
  namespace: zerovm
spec:
  config: '{
            "cniVersion": "0.3.0",
            "name": "zerovm-vlan2",
            "type": "bridge",
            "bridge": "vmbr2",
            "mode": "bridge",
            "ipam": {
                "type": "whereabouts",
                "ipRanges": [{
                    "range": "10.0.2.30-10.0.2.130/24"
                  }],
                "dns": {
                  "nameservers":[
                    "10.1.1.151",
                    "10.1.1.152",
                    "10.1.1.153"
                  ]
                }
              }
           }'
