apiVersion: "tinkerbell.org/v1alpha1"
kind: Hardware
metadata:
  name: robot03
  namespace: tink-system
spec:
  disks:
    - device: /dev/sda
  metadata:
    facility:
      facility_code: onprem
    manufacturer:
      slug: proxmox
    instance:
      userdata: ""
      hostname: "robot03"
      id: "bc:24:11:80:ca:7d"
      operating_system:
        distro: "debian"
        os_slug: "debian_12"
        version: "12"
  interfaces:
    - dhcp:
        arch: x86_64
        hostname: robot03
        ip:
          address: 10.1.2.200
          gateway: 10.1.1.1
          netmask: 255.255.0.0
        lease_time: 86400
        mac: "bc:24:11:80:ca:7d"
        name_servers:
          - 10.1.1.53
        uefi: true
      netboot:
        allowPXE: true
        allowWorkflow: true
