apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: thanos
    meta.helm.sh/release-namespace: thanos
  creationTimestamp: "2024-02-25T21:56:09Z"
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thanos
    app.kubernetes.io/version: 0.34.0
    helm.sh/chart: thanos-13.1.0
  name: thanos-query-frontend
  namespace: thanos
  resourceVersion: "5203357"
  uid: 1a12bb41-d2a4-4cfd-bd4a-72ac9f710769
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.11.57
  clusterIPs:
  - 10.43.11.57
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerSourceRanges:
  - 10.1.0.0/16
  - 100.115.0.0/16
  ports:
  - name: http
    nodePort: 31460
    port: 9090
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/name: thanos
  sessionAffinity: None
  type: LoadBalancer
status:
  conditions:
  - lastTransitionTime: "2024-02-25T21:56:09Z"
    message: ""
    reason: satisfied
    status: "True"
    type: io.cilium/lb-ipam-request-satisfied
  loadBalancer:
    ingress:
    - ip: 10.0.2.202
